services:
  loki:
    labels:
      metrics.grafana.com/scrape: false
    depends_on: { minio: { condition: service_healthy } }
    image: ${LOKI_IMAGE:-docker.io/grafana/loki:3.0.0}
    volumes:
      - ../config/loki:/etc/loki
    command:
      - -config.file=/etc/loki/monolithic-mode-logs.yaml
      - -target=all
      - -config.expand-env=true
    healthcheck:
      test: [ "CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:3100/ready || exit 1" ]
      interval: 3s
      timeout: 1s
      retries: 15
    # expose 33100 port so we can directly access loki inside container
    ports:
      - "33100:3100"
    networks:
      default:
        aliases:
          - loki-memberlist
