# This file can be used to set overrides or other runtime config.
ingester_limits: # limits that each ingester replica enforces
  max_ingestion_rate: 20000
  max_series: 1500000
  max_tenants: 1000
  max_inflight_push_requests: 30000

distributor_limits: # limits that each distributor replica enforces
  max_ingestion_rate: 20000
  max_inflight_push_requests: 30000
  max_inflight_push_requests_bytes: 50000000

overrides:
  anonymous: # limits for anonymous that the whole cluster enforces
    # ingestion_tenant_shard_size: 9
    max_global_series_per_user: 1500000
    max_fetched_series_per_query: 100000
    native_histograms_ingestion_enabled: true
    ruler_max_rules_per_rule_group: 50