# https://grafana.com/docs/oncall/latest/set-up/open-source/#slack-setup
# # lt --port 8080 -s codelab-monitoring-oncall --print-requests
# # Localtunnel will generate an url, e.g. https://codelab-monitoring-oncall.loca.lt
_metadata:
  major_version: 1
  minor_version: 1
display_information:
  name: QC Owl Bot
  background_color: "#400440"
features:
  app_home:
    home_tab_enabled: false
    messages_tab_enabled: true
    messages_tab_read_only_enabled: false
  bot_user:
    display_name: QC Owl Bot
    always_online: true
  shortcuts:
    - name: Add to resolution note
      type: message
      callback_id: add_resolution_note
      description: Add this message to resolution note
  slash_commands:
    - command: /oncall
      url: https://codelab-monitoring-oncall.loca.lt/slack/interactive_api_endpoint/
      description: Direct page a team or user(s)
      should_escape: false
oauth_config:
  redirect_urls:
    - https://codelab-monitoring-oncall.loca.lt/api/internal/v1/complete/slack-install-free/
    - https://codelab-monitoring-oncall.loca.lt/api/internal/v1/complete/slack-login/
  scopes:
    user:
      - channels:read
      - chat:write
      - identify
      - users.profile:read
    bot:
      - app_mentions:read
      - channels:history
      - channels:read
      - chat:write
      - chat:write.customize
      - chat:write.public
      - commands
      - files:write
      - groups:history
      - groups:read
      - im:history
      - im:read
      - im:write
      - mpim:history
      - mpim:read
      - mpim:write
      - reactions:write
      - team:read
      - usergroups:read
      - usergroups:write
      - users.profile:read
      - users:read
      - users:read.email
      - users:write
settings:
  event_subscriptions:
    request_url: https://codelab-monitoring-oncall.loca.lt/slack/event_api_endpoint/
    bot_events:
      - app_home_opened
      - app_mention
      - channel_archive
      - channel_created
      - channel_deleted
      - channel_rename
      - channel_unarchive
      - member_joined_channel
      - message.channels
      - message.im
      - subteam_created
      - subteam_members_changed
      - subteam_updated
      - user_profile_changed
  interactivity:
    is_enabled: true
    request_url: https://codelab-monitoring-oncall.loca.lt/slack/interactive_api_endpoint/
  org_deploy_enabled: false
  socket_mode_enabled: false
  token_rotation_enabled: false
