{
 "title": "Windows Services & Processes",
 "description": "History of service statuses & process metrics",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(windows_os_info,instance)"
    }
   },
   {
    "name": "job",
    "label": "Job Name",
    "query": {
     "query": "label_values(windows_os_info,job)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "CPU per Process",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "((sum(irate(windows_process_cpu_time_total{job=\"$job\", instance=\"$instance\"}[$__rate_interval])) by (process, process_id) / ignoring(process, process_id) group_left sum(windows_cs_logical_processors)) * 100)",
     "legendFormat": "{{process}} ({{process_id}})"
    }
   ]
  },
  {
   "title": "Threads per Process",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "windows_process_thread_count{job=\"$job\", instance=\"$instance\"}",
     "legendFormat": "{{process}} ({{process_id}})"
    }
   ]
  },
  {
   "title": "Handles per Process",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "windows_process_handle_count{job=\"$job\", instance=\"$instance\"}",
     "legendFormat": "{{process}} ({{process_id}})"
    }
   ]
  },
  {
   "title": "Memory Virtual",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "windows_process_virtual_bytes{job=\"$job\", instance=\"$instance\"}",
     "legendFormat": "{{process}} ({{process_id}})"
    }
   ]
  },
  {
   "title": "Memory Working Set",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "windows_process_working_set_bytes{job=\"$job\", instance=\"$instance\"}",
     "legendFormat": "{{process}} ({{process_id}})"
    }
   ]
  },
  {
   "title": "Private Memory",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "windows_process_private_bytes{job=\"$job\", instance=\"$instance\"}",
     "legendFormat": "{{process}} ({{process_id}})"
    }
   ]
  },
  {
   "title": "Swap usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "windows_process_page_file_bytes{job=\"$job\", instance=\"$instance\"}",
     "legendFormat": "{{process}} ({{process_id}})"
    }
   ]
  },
  {
   "title": "Writes per Process",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 63 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "irate(windows_process_io_bytes_total{mode=\"write\", job=\"$job\", instance=\"$instance\"}[$__rate_interval])",
     "legendFormat": "{{process}} ({{process_id}})"
    }
   ]
  },
  {
   "title": "Reads per Process",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 72 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "irate(windows_process_io_bytes_total{mode=\"read\", job=\"$job\", instance=\"$instance\"}[$__rate_interval])",
     "legendFormat": "{{process}} ({{process_id}})"
    }
   ]
  },
  {
   "title": "Other IO per Process",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 81 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "irate(windows_process_io_bytes_total{mode=\"other\", job=\"$job\", instance=\"$instance\"}[$__rate_interval])",
     "legendFormat": "{{process}} ({{process_id}})"
    }
   ]
  }
 ]
}