{
 "title": "Container Drill Down v2",
 "tags": [ "docker-integration" ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "prometheus_datasource", "label": "Data Source", "query": "prometheus" },
   {
    "name": "job",
    "label": "Job",
    "query": "label_values(machine_scrape_error, job)"
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": "label_values(machine_scrape_error{job=~\"$job\"}, instance)"
   },
   {
    "name": "container",
    "label": "Container",
    "query": "label_values(container_last_seen{job=~\"$job\", instance=~\"$instance\"}, name)"
   }
  ]
 },
 "panels": [
  {
   "title": "Overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Total Containers",
     "type": "stat",
     "description": "Total number of running containers last seen by the exporter.",
     "gridPos": { "h": 7, "w": 4, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "count(container_last_seen{job=~\"$job\", instance=~\"$instance\", name=~\"$container\"})"
      }
     ]
    },
    {
     "title": "Total Images",
     "type": "stat",
     "description": "Total number of distinct images found across running containers",
     "gridPos": { "h": 7, "w": 4, "x": 4, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "count (sum by (image) (container_last_seen{job=~\"$job\", instance=~\"$instance\", name=~\"$container\", image=~\".+\"}))"
      }
     ]
    },
    {
     "title": "CPU Utilization by Containers",
     "type": "gauge",
     "description": "Cumulative cpu time consumed in seconds.",
     "gridPos": { "h": 7, "w": 4, "x": 8, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "sum (rate(container_cpu_usage_seconds_total{job=~\"$job\", instance=~\"$instance\", name=~\"$container\"}[$__rate_interval]))"
      }
     ]
    },
    {
     "title": "Memory Reserved by Containers",
     "type": "gauge",
     "description": "Memory reserved by the containers on the machine.",
     "gridPos": { "h": 7, "w": 4, "x": 12, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "sum(container_spec_memory_reservation_limit_bytes{job=~\"$job\", instance=~\"$instance\", name=~\"$container\"}) / avg(machine_memory_bytes{job=~\"$job\", instance=~\"$instance\"})"
      }
     ]
    },
    {
     "title": "Memory Utilization by Containers",
     "type": "gauge",
     "description": "Current memory usage in bytes, including all memory regardless of when it was accessed.",
     "gridPos": { "h": 7, "w": 4, "x": 16, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "sum(container_memory_usage_bytes{job=~\"$job\", instance=~\"$instance\", name=~\"$container\"}) / avg(machine_memory_bytes{job=~\"$job\", instance=~\"$instance\"})"
      }
     ]
    }
   ]
  },
  {
   "title": "Compute",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {}
   ]
  },
  {
   "title": "CPU",
   "type": "timeseries",
   "description": "Cpu time consumed in seconds by container.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "avg by (name) (rate(container_cpu_usage_seconds_total{job=~\"$job\", instance=~\"$instance\", name=~\"$container\"}[$__rate_interval]))",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "timeseries",
   "description": "Current memory usage in bytes, including all memory regardless of when it was accessed by container.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (name) (container_memory_usage_bytes{job=~\"$job\", instance=~\"$instance\", name=~\"$container\"})",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "timeseries",
   "description": "Cpu time consumed in seconds by container.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{job=~\"$job\", instance=~\"$instance\", name=~\"$container\"}[$__rate_interval])) by (cluster)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Major Page Faults (OOM)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "targets": [
    {
     "expr": "sum(rate(container_memory_failures_total{job=~\"$job\", instance=~\"$instance\", name=~\"$container\",failure_type=\"pgmajfault\"}[5m])) by (container)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Network",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Bandwidth",
     "type": "timeseries",
     "description": "The amount of traffic transferred by the network interface.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "sum by (name) (rate(container_network_receive_bytes_total{job=~\"$job\", instance=~\"$instance\", name=~\"$container\"}[$__rate_interval]))",
       "legendFormat": "{{name}} rx"
      },
      {
       "expr": "sum by (name) (rate(container_network_transmit_bytes_total{job=~\"$job\", instance=~\"$instance\", name=~\"$container\"}[$__rate_interval]))",
       "legendFormat": "{{name}} tx"
      }
     ]
    },
    {
     "title": "Dropped Packets",
     "type": "stat",
     "description": "The number of packets that have been dropped at the network interface level.\n\nInbound - packets received but not processed, e.g. due to softnet backlog overflow, bad/unintended VLAN tags, unknown or unregistered protocols, IPv6 frames when the server is not configured for IPv6. Outbound - packets dropped on their way to transmission, e.g. due to lack of resources.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum by (name) (rate(container_network_receive_packets_dropped_total{job=~\"$job\", instance=~\"$instance\", name=~\"$container\"}[$__rate_interval])) > 0",
       "legendFormat": "{{name}} rx"
      },
      {
       "expr": "sum by (name) (rate(container_network_transmit_packets_dropped_total{job=~\"$job\", instance=~\"$instance\", name=~\"$container\"}[$__rate_interval])) > 0",
       "legendFormat": "{{name}} tx"
      }
     ]
    }
   ]
  },
  { "title": "Logs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "Logs",
   "type": "logs",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 20 },
   "targets": [
    {
     "expr": "{container=\"$container\"} | logfmt | line_format `{{ __timestamp__ }} - {{.app}} | {{.error}} {{.err}}{{.request}}`"
    }
   ]
  }
 ]
}