{
 "title": "Docker Logs and Metrics",
 "tags": [ "docker-integration" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "prometheus_datasource", "label": "Data Source", "query": "prometheus" },
   { "name": "loki_datasource", "label": "Loki Data Source", "query": "loki" },
   {
    "name": "job",
    "label": "Job",
    "query": {
     "query": "label_values(machine_scrape_error,job)"
    }
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(machine_scrape_error{job=~\"$job\"},instance)"
    }
   },
   {
    "name": "container",
    "label": "Container",
    "query": {
     "query": "label_values(container_last_seen{instance=~\"$instance\", job=~\"$job\"},name)"
    }
   },
   { "name": "Regen_Search", "label": "Regen Search" },
   {
    "name": "Level",
    "label": "Level",
    "query": {}
   }
  ]
 },
 "panels": [
  {
   "title": "Overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Total Containers",
   "type": "stat",
   "description": "Total number of running containers last seen by the exporter.",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(container_last_seen{job=~\"$job\", instance=~\"$instance\", name=~\"$container\"})"
    }
   ]
  },
  {
   "title": "Total Log Lines",
   "type": "stat",
   "description": "Total number of log lines including errors and ",
   "gridPos": { "h": 7, "w": 6, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time({job=~\"$job\", instance=~\"$instance\", container=~\"$container\"}[$__interval]))"
    }
   ]
  },
  {
   "title": "CPU Utilization by Containers",
   "type": "stat",
   "description": "Cumulative cpu time consumed in seconds.",
   "gridPos": { "h": 6, "w": 12, "x": 11, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum (rate(container_cpu_usage_seconds_total{job=~\"$job\", instance=~\"$instance\", name=~\"$container\"}[$__rate_interval]))"
    }
   ]
  },
  {
   "title": "Memory Utilization by Containers",
   "type": "bargauge",
   "description": "Current memory usage in bytes, including all memory regardless of when it was accessed.",
   "gridPos": { "h": 5, "w": 12, "x": 11, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{job=~\"$job\", instance=~\"$instance\", name=~\"$container\"}) / avg(machine_memory_bytes{job=~\"$job\", instance=~\"$instance\"})"
    },
    {
     "expr": "sum(container_spec_memory_reservation_limit_bytes{job=~\"$job\", instance=~\"$instance\", name=~\"$container\"}) / avg(machine_memory_bytes{job=~\"$job\", instance=~\"$instance\"})"
    }
   ]
  },
  { "title": "Warnings", "gridPos": { "h": 6, "w": 6, "x": 0, "y": 8 } },
  { "title": "Errors", "gridPos": { "h": 6, "w": 4, "x": 6, "y": 8 } },
  { "title": "Bytes Used", "gridPos": { "h": 4, "w": 5, "x": 0, "y": 14 } },
  { "title": "Error Percentage", "gridPos": { "h": 4, "w": 5, "x": 5, "y": 14 } },
  {
   "title": "Historical Logs / Warnings / Errors",
   "gridPos": { "h": 7, "w": 23, "x": 0, "y": 18 }
  },
  {
   "title": "Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU",
     "type": "timeseries",
     "description": "Cpu time consumed in seconds by container.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "avg by (name) (rate(container_cpu_usage_seconds_total{job=~\"$job\", instance=~\"$instance\", name=~\"$container\"}[$__rate_interval]))",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Memory",
     "type": "timeseries",
     "description": "Current memory usage in bytes, including all memory regardless of when it was accessed by container.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum by (name) (container_memory_usage_bytes{job=~\"$job\", instance=~\"$instance\", name=~\"$container\"})",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "CPU",
     "type": "timeseries",
     "description": "Cpu time consumed in seconds by container.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "sum(rate(container_cpu_usage_seconds_total{job=~\"$job\", instance=~\"$instance\", name=~\"$container\"}[$__rate_interval])) by (cluster)",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Major Page Faults (OOM)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
     "targets": [
      {
       "expr": "sum(rate(container_memory_failures_total{job=~\"$job\", instance=~\"$instance\", name=~\"$container\",failure_type=\"pgmajfault\"}[5m])) by (container)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Bandwidth",
     "type": "timeseries",
     "description": "The amount of traffic transferred by the network interface.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 42 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "sum by (name) (rate(container_network_receive_bytes_total{job=~\"$job\", instance=~\"$instance\", name=~\"$container\"}[$__rate_interval]))",
       "legendFormat": "{{name}} rx"
      },
      {
       "expr": "sum by (name) (rate(container_network_transmit_bytes_total{job=~\"$job\", instance=~\"$instance\", name=~\"$container\"}[$__rate_interval]))",
       "legendFormat": "{{name}} tx"
      }
     ]
    },
    {
     "title": "Dropped Packets",
     "type": "stat",
     "description": "The number of packets that have been dropped at the network interface level.\n\nInbound - packets received but not processed, e.g. due to softnet backlog overflow, bad/unintended VLAN tags, unknown or unregistered protocols, IPv6 frames when the server is not configured for IPv6. Outbound - packets dropped on their way to transmission, e.g. due to lack of resources.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 42 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum by (name) (rate(container_network_receive_packets_dropped_total{job=~\"$job\", instance=~\"$instance\", name=~\"$container\"}[$__rate_interval])) > 0",
       "legendFormat": "{{name}} rx"
      },
      {
       "expr": "sum by (name) (rate(container_network_transmit_packets_dropped_total{job=~\"$job\", instance=~\"$instance\", name=~\"$container\"}[$__rate_interval])) > 0",
       "legendFormat": "{{name}} tx"
      }
     ]
    },
    {
     "title": "Panel Title",
     "type": "bargauge",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 50 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "conditions": [
        {
         "evaluator": {
          "params": [
           1,
           0
          ],
          "type": "lt"
         },
         "query": {
          "params": []
         },
         "reducer": {
          "params": [],
          "type": "last"
         },
         "type": "query"
        }
       ],
       "expression": "A",
       "type": "threshold"
      }
     ]
    }
   ]
  },
  { "title": "Logs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "Logs",
   "type": "logs",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 27 },
   "targets": [
    {
     "expr": "{container=\"$container\"} | json | line_format `{{ __timestamp__ }} - {{.app}} | {{.error}} {{.err}}{{.request}}`"
    }
   ]
  },
  { "title": "Full Log File", "gridPos": { "h": 7, "w": 22, "x": 0, "y": 32 } },
  { "title": "Errors", "gridPos": { "h": 7, "w": 23, "x": 0, "y": 39 } },
  { "title": "Warnings", "gridPos": { "h": 8, "w": 22, "x": 0, "y": 46 } },
  {
   "title": "Logs w Regex Filter",
   "type": "logs",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 54 },
   "targets": [
    {
     "expr": "{app=\"$container\"} |= `$Regen_Search` | json | level =~ `$Level` | line_format `{{ __timestamp__ }} - {{.app}} | {{.error}} {{.err}}{{.request}}`"
    }
   ]
  }
 ]
}