server {
    listen 3001;
    listen [::]:3001;

    location = / {
      proxy_pass      http://${NTOPNG_HOST}:3000/;
    }

    location / {
      proxy_pass      http://${NTOPNG_HOST}:3000$request_uri;
    }
}
