---
modules:
  default:
    metrics:
      # Interface stats
      - name: ntopng_interface
        type: object
        path: '{.rsp}'
        help: ntopng interface statistics
        labels:
          ifname: '{.ifname}'
        values:
          bytes_download: '{.bytes_download}'
          bytes_upload: '{.bytes_upload}'
          packets_download: '{.packets_download}'
          packets_upload: '{.packets_upload}'
          num_flows: '{.num_flows}'
          num_hosts: '{.num_hosts}'
          num_local_hosts: '{.num_local_hosts}'
          alerted_flows: '{.alerted_flows}'
          alerted_flows_error: '{.alerted_flows_error}'
          alerted_flows_warning: '{.alerted_flows_warning}'
          drops: '{.drops}'
          throughput_bps: '{.throughput_bps}'
          throughput_pps: '{.throughput_pps}'
          engaged_alerts: '{.engaged_alerts}'
          uptime_sec: '{.uptime_sec}'
      # System host stats
      - name: ntopng_system
        type: object
        path: '{.rsp.system_host_stats}'
        help: ntopng system host statistics
        values:
          cpu_load: '{.cpu_load}'
          mem_used: '{.mem_used}'
          mem_free: '{.mem_free}'
          mem_total: '{.mem_total}'
          mem_ntopng_resident: '{.mem_ntopng_resident}'
          dropped_alerts: '{.dropped_alerts}'
      # TCP packet stats
      - name: ntopng_tcp_packets
        type: object
        path: '{.rsp.tcpPacketStats}'
        help: ntopng TCP packet statistics
        values:
          lost: '{.lost}'
          out_of_order: '{.out_of_order}'
          retransmissions: '{.retransmissions}'
