{
 "title": "Windows System Overview",
 "description": "A dashboard utilizing metrics collected via \"windows_exporter\" for Prometheus.",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(windows_cs_hostname,instance)"
    }
   },
   {
    "name": "job",
    "label": "Job Name",
    "query": {
     "query": "label_values(windows_cs_hostname{job=\"$job\"},job)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Current Values",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Processes",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "windows_os_processes{job=\"integrations/windows_exporter\", instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "time() - windows_system_system_up_time{job=\"$job\", instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "CPU Utilization",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "100 - 100 * (avg(irate(windows_cpu_time_total{mode=\"idle\", job=\"$job\", instance=\"$instance\"}[$__rate_interval])))"
    }
   ]
  },
  {
   "title": "RAM Utilization",
   "type": "gauge",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "100 - 100 * (windows_os_physical_memory_free_bytes{job=\"$job\", instance=\"$instance\"} / windows_cs_physical_memory_bytes{job=\"$job\", instance=\"$instance\"})"
    }
   ]
  },
  {
   "title": "Disc Utilization",
   "type": "gauge",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "100 - 100 * (windows_logical_disk_free_bytes{job=\"$job\", instance=\"$instance\"} / windows_logical_disk_size_bytes{job=\"$job\", instance=\"$instance\"})",
     "legendFormat": "Disc {{volume}}"
    }
   ]
  },
  {
   "title": "Disc Total Reads",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "windows_logical_disk_read_bytes_total{job=\"$job\", instance=\"$instance\"}",
     "legendFormat": "Disc {{volume}}"
    }
   ]
  },
  {
   "title": "Net Utilization",
   "type": "gauge",
   "gridPos": { "h": 3, "w": 3, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "(irate(windows_net_bytes_total{nic!~'isatap.*|VPN.*|.*Pseudo.*', job=\"$job\", instance=\"$instance\"}[$__rate_interval])) * 8 / windows_net_current_bandwidth{nic!~'isatap.*|VPN.*|.*Pseudo.*', job=\"$job\", instance=\"$instance\"} * 100"
    }
   ]
  },
  {
   "title": "Threads",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "windows_system_threads{job=\"$job\", instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "vCPU Cores",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "windows_cs_logical_processors{job=\"$job\", instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "CPU Frequency",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "hertz" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg(windows_cpu_core_frequency_mhz{job=\"$job\", instance=\"$instance\"}) * 1000000"
    }
   ]
  },
  {
   "title": "RAM Total",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "windows_cs_physical_memory_bytes{job=\"$job\", instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Disc Total",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "windows_logical_disk_size_bytes{job=\"$job\", instance=\"$instance\"}",
     "legendFormat": "Disc {{volume}}"
    }
   ]
  },
  {
   "title": "Disc Total Writes",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "windows_logical_disk_write_bytes_total{job=\"$job\", instance=\"$instance\"}",
     "legendFormat": "Disc {{volume}}"
    }
   ]
  },
  {
   "title": " Net Total Transfers",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 20, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "windows_net_bytes_total{nic!~'isatap.*|VPN.*|.*Pseudo.*', job=\"$job\", instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "CPU History",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {}
   ]
  },
  {
   "title": "CPU Utilization Total",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 23, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 - 100 * (avg(irate(windows_cpu_time_total{mode=\"idle\", job=\"$job\", instance=\"$instance\"}[$__rate_interval])))"
    }
   ]
  },
  {
   "title": "CPU Utilization per Mode",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 23, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "avg(irate(windows_cpu_time_total{mode='interrupt', job=\"$job\", instance=\"$instance\"}[$__rate_interval])) * 100",
     "legendFormat": "Interrupts"
    },
    {
     "expr": "avg(irate(windows_cpu_time_total{mode='dcp', job=\"$job\", instance=\"$instance\"}[$__rate_interval])) * 100",
     "legendFormat": "DCP"
    },
    {
     "expr": "avg(irate(windows_cpu_time_total{mode='privileged', job=\"$job\", instance=\"$instance\"}[$__rate_interval])) * 100",
     "legendFormat": "System"
    },
    {
     "expr": "avg(irate(windows_cpu_time_total{mode='user', job=\"$job\", instance=\"$instance\"}[$__rate_interval])) * 100",
     "legendFormat": "User"
    }
   ]
  },
  {
   "title": "CPU Utilization per Core",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 23, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 - 100 * (avg by (core) (irate(windows_cpu_time_total{mode=\"idle\", job=\"$job\", instance=\"$instance\"}[$__rate_interval])))",
     "legendFormat": "Core {{core}}"
    }
   ]
  },
  {
   "title": "CPU Frequency AVG",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 23, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "hertz" } },
   "targets": [
    {
     "expr": "avg(windows_cpu_core_frequency_mhz{job=\"$job\", instance=\"$instance\"} * 1000000)"
    }
   ]
  },
  {
   "title": "Processes Count",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 23, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "windows_os_processes{job=\"$job\", instance=\"$instance\"}",
     "legendFormat": "Value"
    }
   ]
  },
  {
   "title": "Threads Count",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 23, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "windows_system_threads{job=\"$job\", instance=\"$instance\"}",
     "legendFormat": "Value"
    }
   ]
  },
  {
   "title": "Memory History",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 },
   "targets": [
    {}
   ]
  },
  {
   "title": "RAM Utilization",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 23, "x": 0, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 - 100 * (windows_os_physical_memory_free_bytes{job=\"$job\", instance=\"$instance\"} / windows_cs_physical_memory_bytes{job=\"$job\", instance=\"$instance\"})",
     "legendFormat": "Value"
    }
   ]
  },
  {
   "title": "Memory Utilization",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 23, "x": 0, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "windows_os_virtual_memory_bytes{job=\"$job\", instance=\"$instance\"}",
     "legendFormat": "Virtual Total"
    },
    {
     "expr": "windows_cs_physical_memory_bytes{job=\"$job\", instance=\"$instance\"}",
     "legendFormat": "Physical Total"
    },
    {
     "expr": "windows_os_virtual_memory_free_bytes{job=\"$job\", instance=\"$instance\"}",
     "legendFormat": "Virtual Available"
    },
    {
     "expr": "windows_os_physical_memory_free_bytes{job=\"$job\", instance=\"$instance\"}",
     "legendFormat": "Physical Available"
    },
    {
     "expr": "windows_memory_committed_bytes{job=\"$job\", instance=\"$instance\"}",
     "legendFormat": "Commited"
    },
    {
     "expr": "windows_memory_cache_bytes{job=\"$job\", instance=\"$instance\"}",
     "legendFormat": "Cached"
    }
   ]
  },
  {
   "title": "Swap",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 23, "x": 0, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "irate(windows_memory_swap_pages_written_total{job=\"$job\", instance=\"$instance\"}[$__rate_interval]) * 4096",
     "legendFormat": "Writes"
    },
    {
     "expr": "irate(windows_memory_swap_pages_read_total{job=\"$job\", instance=\"$instance\"}[$__rate_interval]) * 4096",
     "legendFormat": "Reads"
    }
   ]
  },
  {
   "title": "Disk History",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 57 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Disc Utilization",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 23, "x": 0, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 - 100 * (windows_logical_disk_free_bytes{job=\"$job\", instance=\"$instance\"} / windows_logical_disk_size_bytes{job=\"$job\", instance=\"$instance\"})",
     "legendFormat": "Disc {{volume}}"
    }
   ]
  },
  {
   "title": "Disc Writes",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 23, "x": 0, "y": 65 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "irate(windows_logical_disk_write_bytes_total{job=\"$job\", instance=\"$instance\"}[$__rate_interval])",
     "legendFormat": "Disc {{volume}}"
    }
   ]
  },
  {
   "title": "Disc Reads",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 23, "x": 0, "y": 71 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "irate(windows_logical_disk_read_bytes_total{job=\"$job\", instance=\"$instance\"}[$__rate_interval])",
     "legendFormat": "Disc {{volume}}"
    }
   ]
  },
  {
   "title": "Network History",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 77 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Network Utilization",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 23, "x": 0, "y": 78 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 * (irate(windows_net_bytes_total{nic!~'isatap.*|VPN.*|.*Pseudo.*', job=\"$job\", instance=\"$instance\"}[$__rate_interval])) * 8 / windows_net_current_bandwidth{nic!~'isatap.*|VPN.*|.*Pseudo.*', job=\"$job\", instance=\"$instance\"}",
     "legendFormat": "Value"
    }
   ]
  },
  {
   "title": "Network Transfers",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 23, "x": 0, "y": 84 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "max by (instance) (irate(windows_net_bytes_received_total{nic!~'isatap.*|VPN.*', job=\"$job\", instance=\"$instance\"}[$__rate_interval]))",
     "legendFormat": "Inbound"
    },
    {
     "expr": "max by (instance) (irate(windows_net_bytes_sent_total{nic!~'isatap.*|VPN.*', job=\"$job\", instance=\"$instance\"}[$__rate_interval]))",
     "legendFormat": "Outbound"
    }
   ]
  }
 ]
}