
services:
  # override included service grafana for dashboards pre-provisioning
  grafana:
    volumes:
      - ../.
    environment:
      GF_DASHBOARDS_DEFAULT_HOME_DASHBOARD_PATH: /var/lib/grafana/dashboards/github-mixin/api-usage.json

  # override included service mimirtool for rules and alerts pre-provisioning
  mimirtool:
    volumes:
      - ../../monitoring-mixins/github-mixin/deploy/github-mixin-rules.yaml:/rules/github-mixin-rules.yaml
      - ../../monitoring-mixins/github-mixin/deploy/github-mixin-alerts.yaml:/rules/github-mixin-alerts.yaml
